version: "3"

services:
  mysql-master:
    image: mysql:8.0
    container_name: proxysql-mysql-replication-master
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sbtest
    volumes:
      - ./master/my.cnf:/etc/mysql/my.cnf
      - ./master/data:/var/lib/mysql
      - ./master/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306

  mysql-slave1:
    image: mysql:8.0
    container_name: proxysql-mysql-replication-slave1
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sbtest
    volumes:
      - ./slave/my-slave1.cnf:/etc/mysql/my.cnf
      - ./slave/data/slave1:/var/lib/mysql
      - ./slave/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3307:3306
    depends_on:
      - mysql-master

  mysql-slave2:
    image: mysql:8.0
    container_name: proxysql-mysql-replication-slave2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sbtest
    volumes:
      - ./slave/my-slave2.cnf:/etc/mysql/my.cnf
      - ./slave/data/slave2:/var/lib/mysql
      - ./slave/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3308:3306
    depends_on:
      - mysql-master

  proxysql:
    image: proxysql/proxysql:2.5.5
    container_name: proxysql-mysql-replication-proxysql
    ports:
      - 6032:6032
      - 6033:6033
    volumes:
      - ./proxysql/proxysql.cnf:/etc/proxysql.cnf

  mysqld-exporter-master:
    image: prom/mysqld-exporter
    container_name: proxysql-mysql-replication-mysqld-exporter-master
    environment:
      - DATA_SOURCE_NAME=exporter:password@(mysql-master:3306)/sbtest
    depends_on:
      - mysql-master
    ports:
      - 9104:9104

  mysqld-exporter-slave1:
    image: prom/mysqld-exporter
    container_name: proxysql-mysql-replication-mysqld-exporter-slave1
    environment:
      - DATA_SOURCE_NAME=exporter:password@(mysql-slave1:3306)/sbtest
    depends_on:
      - mysql-slave1
    ports:
      - 9105:9104

  mysqld-exporter-slave2:
    image: prom/mysqld-exporter
    container_name: proxysql-mysql-replication-mysqld-exporter-slave2
    environment:
      - DATA_SOURCE_NAME=exporter:password@(mysql-slave2:3306)/sbtest
    depends_on:
      - mysql-slave2
    ports:
      - 9106:9104

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
